### ISSUE TITLE
Error when trying to install the version firestore-pdf-generator@0.14.1

### ISSUE THREAD

**Issue by webthurwa** [pdfplum/pdfplum#14]
`{
   "ResourceType": "gcp-types/cloudfunctions-v1:projects.locations.functions",
   "ResourceErrorCode": "400",
   "ResourceErrorMessage": {
      "code": 400,
      "details": [
         {
            "@type": "type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations": [
               {
                  "field": "function",
                  "description": "Invalid JSON payload received. Unknown name \"availableMemoryMB\" at 'function': Cannot find field."
               }
            ]
         }
      ],
      "message": "Invalid JSON payload received. Unknown name \"availableMemoryMB\" at 'function': Cannot find field.",
      "status": "INVALID_ARGUMENT",
      "statusMessage": "Bad Request",
      "requestPath": "https://cloudfunctions.googleapis.com/v1/projects/.../functions",
      "httpMethod": "POST"
   }
}`

**Comment by chethan9** [comment]
what is the solution i am also facing same issue

**Comment by chethan9** [comment]
when will the new version will be live on firebase extension ?? or is there way to manually change when can i expect to get this working

**Comment by sassanh** [comment]
I'm sorry it is causing any annoyance with your workflow.
At the moment the only solution would be to install a previous version like 0.14.0, you need to make sure you set the memory size of the function to 1024MB while installing the extension.

I'm waiting for a reply from Firebase team on this question: https://stackoverflow.com/questions/77269318/to-set-a-minimum-default-value-for-the-memory-of-a-firebase-extension-function and as soon as they provide an answer I will update the extension.
If I don't get an answer there in 2 days I will try to contact Firebase team directly, I hope we can resolve this issue in less than 5 days.

My understanding is that it has happened because of a change in Firebase API which wasn't communicated with extension developers. After all Firebase extension is still in beta stage and this kind of backward incompatible changes in the API are expected.

**Comment by sassanh** [comment]
I think this issue is resolved in the latest rc:
- https://console.firebase.google.com/project/extensions-test-65de3/extensions/install?ref=pdfplum%2Ffirestore-pdf-generator@0.14.2-rc.2
- https://console.firebase.google.com/project/extensions-test-65de3/extensions/install?ref=pdfplum%2Fhttp-pdf-generator@0.14.2-rc.2

Please check it and if it's good we'll publish version 0.14.2

**Comment by webthurwa** [comment]
Yes, this has resolved the issue. Thanks.

**Comment by sassanh** [comment]
Thanks for testing it! I just published version 0.14.2, usually it takes 1 or 2 days for Firebase team to review new versions.
