### ISSUE TITLE
Localization, is there a recommended way to do it?

### ISSUE THREAD

**Issue by julienreszka** [pdfplum/pdfplum#34]
Is there an example of how to implement localization?

**Comment by sassanh** [comment]
Sorry for the late response, I was trying to find the time to prepare a demo for the localization but I couldn't find the time.

While a sample usage or some documented best practices would definitely be helpful for people to get started with localization, pdfplum is not providing any tools itself for this purpose and the tools provided in JS community should be sufficient for this purpose. You may consider i18next for example.

Any pull request adding documentation or sample usage regarding this issue is welcome.
