### ISSUE TITLE
Error TypeError: Cannot read properties of undefined (reading 'toString') during extension run

### ISSUE THREAD

**Issue by kamil-ignac** [pdfplum/pdfplum#38]
### Description

Extension function cannot start because of runtime error. 

### Steps to reproduce the behavior

Just install the extension and try to run it.

### Logs

{
  "textPayload": "Error TypeError: Cannot read properties of undefined (reading 'toString')\n    at helpers.phoneNumber (/workspace/node_modules/handlebars-helpers/lib/number.js:75:13)\n    at Object.wrapper (/workspace/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)\n    at Object.eval [as main] (eval at createFunctionContext (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:25:112)\n    at main (/workspace/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)\n    at ret (/workspace/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)\n    at ret (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)\n    at /workspace/build/lib/load_template.js:97:77\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at process.processImmediate (node:internal/timers:447:9)\n    at process.topLevelDomainCallback (node:domain:161:15)",
  "insertId": "66a55bc9000b7ede21fc673a",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "znesnaze21-beta",
      "function_name": "ext-firestore-pdf-generator-executePdfGenerator",
      "region": "europe-west1"
    }
  },
  "timestamp": "2024-07-27T20:42:49.753374Z",
  "severity": "ERROR",
  "labels": {
    "instance_id": "0087244a803bad11fcfb0bb70e37aba87cb1989a9508015c31900cff570d293a7ff91a20c9b65d119e0d367da6250e88dddc69a0ea5a02aad52b319431dac8373e",
    "execution_id": "h3i3kdc33dr7",
    "runtime_version": "nodejs18_20240720_18_20_4_RC00"
  },
  "logName": "projects/znesnaze21-beta/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/znesnaze21-beta/traces/e2a2efe478276cfb33e81b1b37a3420c",
  "receiveTimestamp": "2024-07-27T20:42:50.039324609Z",
  "errorGroups": [
    {
      "id": "CIycutqEg9a5qwE"
    }
  ]
}

**Comment by sassanh** [comment]
I just installed fresh instances of the extension both for the http version as well as the firestore version and both worked for me without any issues.
I would probably be more helpful if you wrote the reproduction steps so that I could reproduce it on my side, you could include information such as:
1. Which extension has the issue on your side. I used both
2. Which version of it are you using? I used 0.17.1
3. How are you triggering the extension. I triggered the http version with the `wget` command provided in its usage page and the firestore version with a simple document solely having "text" field with a random string as its value.

With the provided information I can't help more.
