### ISSUE TITLE
Is it possible create a multi page pdf file?

### ISSUE THREAD

**Issue by albrave** [pdfplum/pdfplum#42]
### Is your feature request related to a problem? Please describe.

I'm using pdfplum as firebase extension and I'm wondering how can create a multi page pdf considering I have already set 'NO' to this param:
"Should PDFPlum automatically set the document height to fit its content?" 

I always get only the first page

### Describe the solution you'd like

I'd like to know if there's any parameter I should set or any css tag to use.
If I use page-break-after: always; as css attribute, the first page is correctly printed but I don't have the other pages.

**Comment by sassanh** [comment]
@albrave Have you seen [this example](https://github.com/pdfplum/pdfplum/tree/main/template-samples/demo) generating [this](https://github.com/pdfplum/pdfplum/blob/main/template-samples/demo.pdf)?

It should give you some idea of how to have your template rendered in multiple pages; alternatively, you can run it for yourself locally and remove its content and add what you want to it step by step.

Since we have that example working, it's evidence that this is supported in pdfplum, so I go ahead and close this issue; we can continue our conversation in the closed issue, though.

**Comment by albrave** [comment]
Hi @sassanh, thanks for your quick answer. 
My bad, I was wrongly sending 'adjustHeightToFit' as true. Just changed to 'false' and everything is working as expecting.
Thanks again for what you developed and you're doing with this library. In my opinion, it's the best I ever used!
